using UnityEngine;
using System.Collections.Generic;

namespace Modelular.Runtime
{
    // Specify the menu item name that will be added under the "Add new modifier" button;
    [ModelularInterface("Primitives/Disk")]
    public class Disk : Modifier, IPrimitive
    {
        #region Properties
        // Use this attribute to setup default values in the inspector : Simply add the right operand of the = operator as a string.
        [ModelularDefaultValue("DefaultPrimitiveProperties.Default()")]
        public DefaultPrimitiveProperties DefaultParameters { get; set; } = DefaultPrimitiveProperties.Default();
        [ModelularDefaultValue("0.5f")]
        [Min(0f)]
        public float Radius { get; set; } = 0.5f;
        [ModelularDefaultValue("16")]
        [Min(3)]
        public int Subdivisions { get; set; } = 16;
        [ModelularDefaultValue("1f")]
        [Range(0f, 1f)]
        public float Arc { get; set; } = 1f;

        #endregion

        
        #region Methods
        public override StackElement Bake(StackElement previousResult)
        {
            int vCount = ExpectedVertexCount();
            if (!IgnoreVertexLimits)
                GlobalSettings.DetectVertexCountLimitations(vCount);

            List<Polygon> obj = Make();
            obj = (this as IPrimitive).ApplyDefaultParameters(obj);


            previousResult.AddPolygons(obj);
            return previousResult;
        }

        private List<Polygon> Make()
        {
            // Add your polygons to this list
            List<Polygon> result = new();
            // Add your vertices to this array
            Vertex[] vertices = new Vertex[ExpectedVertexCount()];

            int arc = 0;
            if (Arc < 1)
                arc = 1;
            // Create your primitive (vertices + polygons) here
            for (int i = 0; i < Subdivisions + arc; i++)
            {
                var v = Vertex.VertexFromPolarCoord(Radius, 0f, (i * 2f * Mathf.PI * Arc) / Subdivisions);
                vertices[Subdivisions - 1 - i + arc * 2] = v;
                vertices[Subdivisions - 1 - i + arc * 2].normal = Vector3.up;
                vertices[Subdivisions - 1 - i + arc * 2].UV0 = new Vector2(v.x / 2 / Radius + 0.5f, v.z / 2 / Radius + 0.5f);
            }
            if (Arc < 1)
                vertices[0] = new Vertex(Vector3.zero, Vector3.up, UV0:Vector2.one/2);
            result.Add(new Polygon(vertices));

            return result;
        }

        private int ExpectedVertexCount()
        {
            // Specify here how much vertices will get generated by this primitive
            if (Arc < 1)
                return Subdivisions + 2;
            return Subdivisions;
        }

        #endregion
    }
}